import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Page Tems | Next up',
    description: 'Generated by create next app',
  }

  
export default function Tems() {
    return (
      <h1>
        Tems page
      </h1>
    )
  }
  
  